<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implement hook_views_query_alter
 */

function uniagustiniana_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
    switch ($view->id()) {
        case 'grupo_contenido':
            if($view->getDisplay()->display['id'] == 'block_1' 
            || $view->getDisplay()->display['id'] == 'block_4'){
                $current_path = \Drupal::service('path.current')->getPath();
                $path_args = explode('/', $current_path);
                if ($path_args[1] == 'node' && is_numeric($path_args[2])) {
                    $id_query = db_select('groups_field_data', 'g');
                    $id_query->addField('g', 'id');
                    $id_query->join('group_content_field_data', 'gd', 'g.id = gd.gid');
                    $id_query->join('node_field_data', 'nd', 'gd.entity_id = nd.nid');
                    $id_query->condition('nd.nid', $path_args[2],'=');
                    $result = $id_query->execute()->fetchObject();
                    if($result && $result->id){
                        foreach ($query->where as &$condition_group) {
                            foreach ($condition_group['conditions'] as &$condition) {
                                if ($condition['field'] == 'groups_field_data.id') {
                                    $condition = array(
                                        'field' => 'groups_field_data.id',
                                        'value' => $result->id,
                                        'operator' => '=',
                                    );
                                }
                            }
                        }
                    }
                }
            }
        break;
    }
}

/**
 * Implements hook_theme().
 */
function uniagustiniana_theme($existing, $type, $theme, $path) {
	return [
		'pdf_documents' => [
			'variables' => [
				'pdfs' => null
			]
        ],
        'programas_facultad' => [
            'variables' => [
                'programas' => null 
            ]
        ]
	];
}